services:
  newsnow-plus:
    image: ghcr.io/imxv/newsnow-plus:latest
    container_name: newsnow-plus
    ports:
      - '4444:4444'
    volumes:
      - newsnow_plus_data:/usr/app/.data
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - PRODUCTHUNT_API_TOKEN=

volumes:
  newsnow_plus_data:
    name: newsnow_plus_data
